version: "3.8"

services:
  app:
    image: yiisoftware/yii2-php:8.2-apache
    container_name: app
    ports:
      - 8000:80
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=
    volumes:
      - ./mysql:/var/lib/mysql
